import { Arizonia, Urbanist } from "next/font/google";
import "./globals.css";
import Nav from "@/components/custom/Nav";
import FooterSection from "@/components/custom/Footer";
import CopyRightSection from "@/components/custom/CopyRightSection";
import { Toaster } from "@/components/ui/toaster";
import SessionWrapper from "@/lib/SessionWrapper";
import { getServerSession } from "next-auth";
import Script from "next/script";

const arizonia = Arizonia({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-arizonia",
});
const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-urbanist",
});

/* export const metadata = {
  title: "ECom-Store Front",
  description: "Generated by create next app",
}; */

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={`${urbanist.variable} ${arizonia.variable}`}>
        <SessionWrapper session={session}>
          <Nav />
          {children}
          <FooterSection />
          <CopyRightSection />
          <Toaster />
        </SessionWrapper>
      </body>
      <Script
        src="https://www.payhere.lk/lib/payhere.js"
        type="text/javascript"
        strategy="lazyOnload"
      />
    </html>
  );
}
